### ISSUE TITLE
Error when try to get document property

### ISSUE THREAD

**Issue by windyinwind** [swestmoreland/office-document-properties#1]
The errors are mainly:
 invalid comment length. expected: 34010. found: 0 
and 
end of central directory record signature not found

Don't know why this happened. The doc files are all normal files. Nothing special.
![error](https://user-images.githubusercontent.com/6670397/35714988-3087686c-0813-11e8-8095-d57095b35db8.png)

**Comment by swestmoreland** [comment]
This module only works on the more recent Microsoft Office Open XML document formats (docx, docm, pptx, pptm, xlsx, xlsm).
